import React, { useEffect, useState, useRef } from 'react';
import './secondpage.css'; // Assuming you have a secondpage.css file for styling
import imgurl from '../media/pf1.jpg';
import imgtur from '../media/turing-logo.jpg'
import imgfcr from '../media/FocurR_arrow.png'

function FadeInSection(props) {
  const [isVisible, setVisible] = useState(false);
  const domRef = useRef();

  useEffect(() => {
    const observer = new IntersectionObserver(
      (entries) => {
        entries.forEach((entry) => {
          if (entry.intersectionRatio >= 0.3) {
            setVisible(true);
            observer.disconnect(); // Stop observing once visible
          }
        });
      },
      { threshold: 0.3 } // Trigger when 30% of the element is visible
    );

    if (domRef.current) {
      observer.observe(domRef.current);
    }

    return () => {
      if (observer && domRef.current) {
        observer.unobserve(domRef.current);
      }
    };
  }, []);

  return (
    <div
      className={`fade-in-section ${isVisible ? "is-visible" : ""}`}
      ref={domRef}
    >
      {props.children}
    </div>
  );
}

const SecondPage = () => {
  return (
    <div className="sp-big-container">
      {/* <FadeInSection> */}
      <div className="spcontainer3">
      <h2 className="spabm">
      <h3 className='sph3'>About Me</h3> 
      <FadeInSection>
      Hello, welcome to my portfolio! I am an engineer with a B.Tech degree in AI. I enjoy designing and developing end-to-end applications, working on AI, and taking photos. You can explore my work on this page.
       </FadeInSection>
      </h2>
      </div>
        <div style={{ display: 'flex' }}>
          <div className="spcontainer1">
            {/* <h3 className="sph3">About me:</h3> */}
            <h2 className="sph2">
              <h3 className='sph3'>I know:</h3> 
              <FadeInSection>
              <h3 className='spabm'>
                Python, MATLAB, SQL, Git, TensorFlow, PyTorch,HTML, CSS, Reactjs, MySQL, Django RestFramework, Flask, MongoDB.
              </h3>
              </FadeInSection>
            </h2>
          </div>

          <div className="spcontainer2">
  <h2 className="sph2">
    <h3 className="sph3">Experience:</h3>
    <FadeInSection>
    <div className="experience-item">
      
      <div className="job-details">
      <a href="https://www.turing.com" target="_blank" rel="noopener noreferrer">
        <img src={imgtur} alt="Turing Logo" className="company-logo" />
      </a>
        <p className="job-title">Turing - Data Analyst</p>
        <p className="job-date">Aug 2024 – Present</p>
      </div>
      <p className="job-description">
        Analyzed Python code from back-end, data science, and machine learning domains generated by LLMs, 
        reporting inefficiencies and limitations in coding capabilities to clients including Apple, Amazon, and ByteDance.
      </p>
    </div>
   

    <div className="experience-item">
     
      <div className="job-details">
      <a href="https://www.focusrtech.com" target="_blank" rel="noopener noreferrer">
        <img src={imgfcr} alt="FocusR Logo" className="company-logo" />
      </a>
        <p className="job-title">FocusR - Python and AI Developer (Internship)</p>
        <p className="job-date">Feb 2024 – May 2024</p>
      </div>
      <p className="job-description">
        Built a Large Language Model (LLM)-powered hiring application using React.js for the front-end and Django REST 
        Framework for the back-end. Integrated LLM technology for advanced candidate shortlisting.
      </p>
    </div>
    </FadeInSection>
  </h2>
</div>


        </div>
      {/* </FadeInSection> */}

     
    </div>
  );
};

export default SecondPage;